//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ItemMaster()
        {
            this.tbl_DeliveryChallanInner = new HashSet<tbl_DeliveryChallanInner>();
            this.tbl_PurchaseBillInner = new HashSet<tbl_PurchaseBillInner>();
            this.tbl_PurchaseOrderInner = new HashSet<tbl_PurchaseOrderInner>();
            this.tbl_QuotationInner = new HashSet<tbl_QuotationInner>();
            this.tbl_SaleInvoiceInner = new HashSet<tbl_SaleInvoiceInner>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string HSNCode { get; set; }
        public string BasicUnit { get; set; }
        public string SecondaryUnit { get; set; }
        public string ItemCode { get; set; }
        public string ItemCategory { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string TaxForSale { get; set; }
        public Nullable<double> SaleTaxAmount { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public string TaxForPurchase { get; set; }
        public Nullable<double> PurchaseTaxAmount { get; set; }
        public Nullable<double> OpeningQty { get; set; }
        public Nullable<double> atPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ItemLocation { get; set; }
        public Nullable<double> TrackingMRP { get; set; }
        public string BatchNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> MFgdate { get; set; }
        public Nullable<System.DateTime> Expdate { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public byte[] Image1 { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<double> Cess { get; set; }
        public Nullable<double> Profit { get; set; }
    
        public virtual tbl_CategoryMaster tbl_CategoryMaster { get; set; }
        public virtual tbl_CategoryMaster tbl_CategoryMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DeliveryChallanInner> tbl_DeliveryChallanInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseBillInner> tbl_PurchaseBillInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseOrderInner> tbl_PurchaseOrderInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuotationInner> tbl_QuotationInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleInvoiceInner> tbl_SaleInvoiceInner { get; set; }
    }
}
