//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OtherIncomeInner
    {
        public int ID1 { get; set; }
        public string ItemName { get; set; }
        public Nullable<System.DateTime> SalePrice { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<bool> DeleteData { get; set; }
    }
}
