//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Expenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Expenses()
        {
            this.tbl_ExpensesInner = new HashSet<tbl_ExpensesInner>();
        }
    
        public int ID1 { get; set; }
        public string ExpenseCategory { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<double> Total { get; set; }
        public string AdditinalFeild1 { get; set; }
        public string AdditionalFeild2 { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Status { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
    
        public virtual tbl_ExpenseCategory tbl_ExpenseCategory { get; set; }
        public virtual tbl_Expenses tbl_Expenses1 { get; set; }
        public virtual tbl_Expenses tbl_Expenses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ExpensesInner> tbl_ExpensesInner { get; set; }
    }
}
