//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompanyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CompanyMaster()
        {
            this.tbl_LoanBank = new HashSet<tbl_LoanBank>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public string ReferaleCode { get; set; }
        public string BusinessType { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string GSTNumber { get; set; }
        public string OwnerName { get; set; }
        public byte[] Signature { get; set; }
        public byte[] AddLogo { get; set; }
        public string AdditinalFeild1 { get; set; }
        public string AdditinalFeild2 { get; set; }
        public string AdditinalFeild3 { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> Defulatcompany { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LoanBank> tbl_LoanBank { get; set; }
       
    }
}
