//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleInvoiceInner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SaleInvoiceInner()
        {
            this.tbl_SaleInvoice = new HashSet<tbl_SaleInvoice>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public string BasicUnit { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string TaxForSale { get; set; }
        public Nullable<double> SaleTaxAmount { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> freeQty { get; set; }
        public string Discount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<int> ItemAmount { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryType { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<double> stock { get; set; }
        public Nullable<int> Count1 { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> CalTotal { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> IGST { get; set; }
    
        public virtual tbl_CategoryMaster tbl_CategoryMaster { get; set; }
        public virtual tbl_ItemMaster tbl_ItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleInvoice> tbl_SaleInvoice { get; set; }
        public virtual tbl_SaleInvoice tbl_SaleInvoice1 { get; set; }
        public virtual tbl_SaleInvoiceInner tbl_SaleInvoiceInner1 { get; set; }
        public virtual tbl_SaleInvoiceInner tbl_SaleInvoiceInner2 { get; set; }
    }
}
