//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanBank
    {
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string Description { get; set; }
        public string LendarBank { get; set; }
        public string FirmName { get; set; }
        public Nullable<double> CurrentBal { get; set; }
        public Nullable<System.DateTime> BalAsOf { get; set; }
        public string LoanReceive { get; set; }
        public string Interest { get; set; }
        public string Duration { get; set; }
        public Nullable<double> ProcessingFees { get; set; }
        public string PaidBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual tbl_CompanyMaster tbl_CompanyMaster { get; set; }
    }
}
