//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemAdjustement
    {
        public int ID { get; set; }
        public string ItemName { get; set; }
        public string AdjustmentType { get; set; }
        public Nullable<System.DateTime> AdjustmentDate { get; set; }
        public Nullable<double> AtPrice { get; set; }
        public string Quantity { get; set; }
        public string Details { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
    }
}
