//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_SaleOrderInner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SaleOrderInner()
        {
            this.tbl_SaleOrder2 = new HashSet<tbl_SaleOrder>();
        }
    
        public int ID { get; set; }
        [Display(Name = "ItemName")]
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public string BasicUnit { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public string TaxForSale { get; set; }
        public Nullable<double> SaleTaxAmount { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> freeQty { get; set; }
        public string Discount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<int> ItemAmount { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryType { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> IGST { get; set; }
        public Nullable<double> ItemTotal { get; set; }
    
        public virtual tbl_CategoryMaster tbl_CategoryMaster { get; set; }
        public virtual tbl_SaleOrder tbl_SaleOrder { get; set; }
        public virtual tbl_SaleOrder tbl_SaleOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleOrder> tbl_SaleOrder2 { get; set; }
        public virtual tbl_SaleOrderInner tbl_SaleOrderInner1 { get; set; }
        public virtual tbl_SaleOrderInner tbl_SaleOrderInner2 { get; set; }
    }
}
