//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CategoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CategoryMaster()
        {
            this.tbl_ItemMaster = new HashSet<tbl_ItemMaster>();
            this.tbl_ItemMaster1 = new HashSet<tbl_ItemMaster>();
            this.tbl_PurchaseBill = new HashSet<tbl_PurchaseBill>();
            this.tbl_PurchaseOrder = new HashSet<tbl_PurchaseOrder>();
            this.tbl_SaleInvoice = new HashSet<tbl_SaleInvoice>();
            this.tbl_SaleOrder = new HashSet<tbl_SaleOrder>();
            this.tbl_CreditNote1 = new HashSet<tbl_CreditNote1>();
            this.tbl_DebitNote = new HashSet<tbl_DebitNote>();
            this.tbl_DeliveryChallan = new HashSet<tbl_DeliveryChallan>();
            this.tbl_PurchaseBillInner = new HashSet<tbl_PurchaseBillInner>();
            this.tbl_PurchaseOrderInner = new HashSet<tbl_PurchaseOrderInner>();
            this.tbl_SaleInvoiceInner = new HashSet<tbl_SaleInvoiceInner>();
            this.tbl_SaleOrderInner = new HashSet<tbl_SaleOrderInner>();
            this.tblQuotations = new HashSet<tblQuotation>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemMaster> tbl_ItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemMaster> tbl_ItemMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseBill> tbl_PurchaseBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseOrder> tbl_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleInvoice> tbl_SaleInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleOrder> tbl_SaleOrder { get; set; }
        public virtual tbl_CategoryMaster tbl_CategoryMaster1 { get; set; }
        public virtual tbl_CategoryMaster tbl_CategoryMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CreditNote1> tbl_CreditNote1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DebitNote> tbl_DebitNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DeliveryChallan> tbl_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseBillInner> tbl_PurchaseBillInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseOrderInner> tbl_PurchaseOrderInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleInvoiceInner> tbl_SaleInvoiceInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleOrderInner> tbl_SaleOrderInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotation> tblQuotations { get; set; }
    }
}
