//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAndInentoryWeb_Application.Models
{
    using System;
    using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
	using System.Web.Security;
    using System.Web.Mvc;
	public partial class tbl_BankAccount
    {
        [Display(Name = "BankName")]
        public int ID { get; set; }	
		public string AccountName { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<double> OpeningBal { get; set; }
        public static IEnumerable<SelectListItem> ListOfAccount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> DeleteData { get; set; }
        public Nullable<int> Company_ID { get; set; }
       
    }
}
